### ISSUE TITLE
ClientIdentity methods results in null pointer

### ISSUE THREAD

**Issue by HFR1994** [wearetheledger/fabric-mock-stub#17]
When instantiating a ClientIdentity(stub) class you received a Null Pointer since it can't get a Buffer data from a function which already returns a Buffer.

On the file node_modules\fabric-shim\lib\chaincode.js line 238 `signingId.getIdBytes()` returns already a Buffer, so the method `.toBuffer()` causes the program to crash.

Stacktrace:

```
TypeError: signingId.getIdBytes(...).toBuffer is not a function
    at new ClientIdentity (node_modules/fabric-shim/lib/chaincode.js:238:40)
    at Chaincode.<anonymous> (src/InTran.ts:30:25)
    at Generator.next (<anonymous>)
    at /mnt/c/Users/frhec/Documents/IBM/Hyperledger/Internal_Chaincode/src/InTran.ts:12:71
    at new Promise (<anonymous>)
    at __awaiter (src/InTran.ts:8:12)
    at Chaincode.Invoke (src/InTran.ts:42:16)
    at ChaincodeMockStub.<anonymous> (node_modules/@theledger/fabric-mock-stub/src/ChaincodeMockStub.ts:193:35)
    at step (node_modules/@theledger/fabric-mock-stub/dist/ChaincodeMockStub.js:32:23)
    at Object.next (node_modules/@theledger/fabric-mock-stub/dist/ChaincodeMockStub.js:13:53)
    at /mnt/c/Users/frhec/Documents/IBM/Hyperledger/Internal_Chaincode/node_modules/@theledger/fabric-mock-stub/dist/ChaincodeMockStub.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (node_modules/@theledger/fabric-mock-stub/dist/ChaincodeMockStub.js:3:12)
    at ChaincodeMockStub.mockInvoke (node_modules/@theledger/fabric-mock-stub/dist/ChaincodeMockStub.js:199:16)
    at Object.<anonymous> (src/Test.ts:24:24)
    at Generator.next (<anonymous>)
    at /mnt/c/Users/frhec/Documents/IBM/Hyperledger/Internal_Chaincode/src/Test.ts:7:71
    at new Promise (<anonymous>)
    at __awaiter (src/Test.ts:3:12)
    at Context.it (src/Test.ts:21:39)
```

Issue can't be resolve by removing `.toBuffer()` from `.getIdBytes()`, on shorterm. Or as the method dictates the `.getIdBytes()` should return Bytes instead of Buffer.

**Comment by kosullivansita** [comment]
Pull request https://github.com/wearetheledger/fabric-mock-stub/pull/18 created to fix this.

**Comment by joshuavines** [comment]
Just hit this exact issue. Is there a time frame on when the fix will be published?

**Comment by sneljo1** [comment]
@Th1rstyGiant  Will be doing some work on this hopefully on Tuesday
